### ISSUE TITLE
Cannot run npm start

### ISSUE THREAD

**Issue by developer239** [ModusCreateOrg/budgeting-sample-app-webpack2#14]
```
C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:385
                throw e;
                ^

Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "exclude": {},
  "use": "file-loader",
  "query": {
    "name": "[name].[ext]"
  }
}
    at Function.RuleSet.normalizeRule (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\RuleSet.js:168:9)
    at C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\RuleSet.js:83:19
    at Array.map (native)
    at Function.RuleSet.normalizeRules (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\RuleSet.js:82:16)
    at new RuleSet (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\RuleSet.js:75:23)
    at new NormalModuleFactory (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\NormalModuleFactory.js:47:17)
    at Compiler.createNormalModuleFactory (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\Compiler.js:438:28)
    at Compiler.newCompilationParams (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\Compiler.js:451:29)
    at Compiler.compile (C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\Compiler.js:460:20)
    at C:\Projekty\budgeting-sample-app-webpack2-master\node_modules\webpack\lib\Compiler.js:47:17

npm ERR! webpack2-react-redux-budget-app-sample@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack2-react-redux-budget-app-sample@1.0.0 start script.
npm ERR! This is most likely a problem with the webpack2-react-redux-budget-app-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls webpack2-react-redux-budget-app-sample
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\Projekty\budgeting-sample-app-webpack2-master
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Projekty\budgeting-sample-app-webpack2-master\npm-debug.log
npm ERR! not ok code 0

```

**Comment by miguelbermudez** [comment]
Had the same issue. Read https://github.com/webpack/webpack/issues/3645 for the fix.

**Comment by grgur** [comment]
This is related to an update in webpack 2. PR welcome :)

**Comment by grgur** [comment]
All fixed, thanks @Ugarz
