### ISSUE TITLE
Lint Task does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [ModusCreateOrg/budgeting-sample-app-webpack2#46]
Hello,

The Lint Task does not seem to work, when I run "yarn run lint" I get the following error:

```
/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "no-restricted-syntax" is invalid:
	Value "[object Object]" must be an enum value.

Referenced from: /Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint-config-airbnb-base/index.js
Referenced from: eslint-config-airbnb
Referenced from: /Users/markpaul/Documents/Source/Research/testagain/.eslintrc
Error: /Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "no-restricted-syntax" is invalid:
	Value "[object Object]" must be an enum value.

Referenced from: /Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint-config-airbnb-base/index.js
Referenced from: eslint-config-airbnb
Referenced from: /Users/markpaul/Documents/Source/Research/testagain/.eslintrc
    at validateRuleOptions (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (native)
    at Object.validate (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-file.js:529:19)
    at configExtends.reduceRight.e (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-file.js:536:22)
    at configExtends.reduceRight.e (/Users/markpaul/Documents/Source/Research/testagain/node_modules/eslint/lib/config/config-file.js:391:36)
✨  Done in 1.46s.
```

**Comment by newbreedofgeek** [comment]
Actually I worked it out.
There is an incorrect peer dependency.
You need to upgrade eslint like so:
`yarn upgrade eslint@3.19.0`
